# Generated by Django 5.1.4 on 2026-05-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=64, unique=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denom', models.CharField(db_index=True, max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_native', models.BooleanField(default=False)),
                ('token_verification', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('decimals', models.IntegerField(default=18)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=64)),
                ('override_symbol', models.CharField(blank=True, db_index=True, max_length=64)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('coin_gecko_id', models.CharField(blank=True, max_length=128)),
                ('token_type', models.CharField(blank=True, max_length=64)),
                ('external_logo', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
