# Generated by Django 5.1.4 on 2026-05-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_scamwallet_verifiedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('wallet_address', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=64)),
                ('skills', models.TextField(blank=True)),
                ('images', models.TextField(blank=True)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('discord_tag', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=32)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, db_index=True, max_length=255)),
                ('time', models.CharField(blank=True, max_length=64)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('amount', models.CharField(blank=True, max_length=128)),
                ('info', models.TextField(blank=True)),
                ('group', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('injective_role', models.CharField(blank=True, max_length=255)),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('availability', models.CharField(blank=True, max_length=64)),
                ('monthly_rate', models.CharField(blank=True, max_length=64)),
                ('skills', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('discord', models.CharField(blank=True, max_length=128)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('telegram', models.CharField(blank=True, max_length=128)),
                ('x', models.CharField(blank=True, max_length=128)),
                ('github', models.CharField(blank=True, max_length=255)),
                ('wallet_address', models.CharField(db_index=True, max_length=64)),
                ('wallet_type', models.CharField(blank=True, max_length=64)),
                ('nft_holdings', models.TextField(blank=True)),
                ('token_holdings', models.TextField(blank=True)),
                ('portfolio', models.CharField(blank=True, max_length=500)),
                ('cv', models.CharField(blank=True, max_length=500)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=32)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
