name: Deploy Pedro Coin Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env file
        run: |
          cat << EOF > pedroproject/.env
          # Discord Bot Configuration
          DISCORD_BOT=${{ secrets.DISCORD_BOT}}
          DISCORD_BURN_WEBHOOK=${{ secrets.DISCORD_BURN_WEBHOOK }}
          EOF

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Secure Copy .env to Server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "pedroproject/.env"
          target: "/home/${{ secrets.SSH_USER }}/pedroproject/.env"
          rm: true

      - name: Set secure permissions
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ${{ secrets.SSH_PRIVATE_KEY }} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "chmod 600 /home/${{ secrets.SSH_USER }}/pedroproject/.env"

      - name: Restart Application Service
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ${{ secrets.SSH_PRIVATE_KEY }} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "cd /home/${{ secrets.SSH_USER }}/pedroproject && \
               sudo systemctl restart gunicorn && \
               sudo systemctl status gunicorn"

      - name: Clean up local .env
        run: rm -f pedroproject/.env

      - name: Verify deployment
        run: |
          echo "Deployment to ${{ secrets.SSH_HOST }} completed successfully"
          echo "Service restarted: gunicorn"